# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'model_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13model_service.proto\x12\x0cmodelservice\"\x1c\n\nFloatArray\x12\x0e\n\x06values\x18\x01 \x03(\x02\"6\n\x0c\x46loatArray2D\x12&\n\x04rows\x18\x01 \x03(\x0b\x32\x18.modelservice.FloatArray\"_\n\x13VerifyTokensRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\x12\x34\n\x10generated_logits\x18\x02 \x01(\x0b\x32\x1a.modelservice.FloatArray2D\"/\n\x14VerifyTokensResponse\x12\x17\n\x0fverified_tokens\x18\x01 \x01(\t\"/\n\x19PrepareSpeculativeRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\"2\n\x1aPrepareSpeculativeResponse\x12\x14\n\x0c\x66irst_tokens\x18\x01 \x01(\t\"(\n\x16GenerateContentRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"1\n\x17GenerateContentResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t2\xae\x02\n\x0cModelService\x12^\n\x0fGenerateContent\x12$.modelservice.GenerateContentRequest\x1a%.modelservice.GenerateContentResponse\x12U\n\x0cVerifyTokens\x12!.modelservice.VerifyTokensRequest\x1a\".modelservice.VerifyTokensResponse\x12g\n\x12PrepareSpeculative\x12\'.modelservice.PrepareSpeculativeRequest\x1a(.modelservice.PrepareSpeculativeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOATARRAY']._serialized_start=37
  _globals['_FLOATARRAY']._serialized_end=65
  _globals['_FLOATARRAY2D']._serialized_start=67
  _globals['_FLOATARRAY2D']._serialized_end=121
  _globals['_VERIFYTOKENSREQUEST']._serialized_start=123
  _globals['_VERIFYTOKENSREQUEST']._serialized_end=218
  _globals['_VERIFYTOKENSRESPONSE']._serialized_start=220
  _globals['_VERIFYTOKENSRESPONSE']._serialized_end=267
  _globals['_PREPARESPECULATIVEREQUEST']._serialized_start=269
  _globals['_PREPARESPECULATIVEREQUEST']._serialized_end=316
  _globals['_PREPARESPECULATIVERESPONSE']._serialized_start=318
  _globals['_PREPARESPECULATIVERESPONSE']._serialized_end=368
  _globals['_GENERATECONTENTREQUEST']._serialized_start=370
  _globals['_GENERATECONTENTREQUEST']._serialized_end=410
  _globals['_GENERATECONTENTRESPONSE']._serialized_start=412
  _globals['_GENERATECONTENTRESPONSE']._serialized_end=461
  _globals['_MODELSERVICE']._serialized_start=464
  _globals['_MODELSERVICE']._serialized_end=766
# @@protoc_insertion_point(module_scope)
