# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protos.service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BatchServiceStub(object):
    """Define the BatchService service with fully qualified message names
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyRequest = channel.unary_unary(
                '/protos.BatchService/VerifyRequest',
                request_serializer=service__pb2.VerifyRequest.SerializeToString,
                response_deserializer=service__pb2.VerifyResultResponse.FromString,
                _registered_method=True)
        self.InitRequest = channel.unary_unary(
                '/protos.BatchService/InitRequest',
                request_serializer=service__pb2.InitRequest.SerializeToString,
                response_deserializer=service__pb2.InitRequestResponse.FromString,
                _registered_method=True)
        self.DeleteRequest = channel.unary_unary(
                '/protos.BatchService/DeleteRequest',
                request_serializer=service__pb2.InitRequest.SerializeToString,
                response_deserializer=service__pb2.DeleteRequestResponse.FromString,
                _registered_method=True)


class BatchServiceServicer(object):
    """Define the BatchService service with fully qualified message names
    """

    def VerifyRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyRequest,
                    request_deserializer=service__pb2.VerifyRequest.FromString,
                    response_serializer=service__pb2.VerifyResultResponse.SerializeToString,
            ),
            'InitRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.InitRequest,
                    request_deserializer=service__pb2.InitRequest.FromString,
                    response_serializer=service__pb2.InitRequestResponse.SerializeToString,
            ),
            'DeleteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRequest,
                    request_deserializer=service__pb2.InitRequest.FromString,
                    response_serializer=service__pb2.DeleteRequestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.BatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protos.BatchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BatchService(object):
    """Define the BatchService service with fully qualified message names
    """

    @staticmethod
    def VerifyRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.BatchService/VerifyRequest',
            service__pb2.VerifyRequest.SerializeToString,
            service__pb2.VerifyResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.BatchService/InitRequest',
            service__pb2.InitRequest.SerializeToString,
            service__pb2.InitRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.BatchService/DeleteRequest',
            service__pb2.InitRequest.SerializeToString,
            service__pb2.DeleteRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
